data: cifar10
arch: vgg16
use_torchvision: False
use_amp: True
mode: bayesian
aug: True
use_cutmix: False 
use_cutmix: False
size: 32
workers: 4
epochs: 800
start_epoch: 0
batch_size: 256
lr: 0.001 #0.001很重要，调大一些就不收敛了了
step_size: 50
warmup: False
labelsmoothing: False
smoothing: 0.1
optimizer: adam
scheduler: cos
momentum: 0.9
weight_decay: 0 #不能加权重衰减
saved_models: "saved_models"
logs: "logs/"
resume: True 
evaluate:  False 
pretrained: False 
world_size: 1
rank: 0 
dist_backend: "nccl"
gpu: 1
multiprocessing_distributed: False 
print_freq: 50
seed: 107
num_monte_carlo: 20
num_mc: 1
prior_mu: 0.0
prior_sigma: 1.0
posterior_mu_init: 0.0
bnn_rho_init: -3.0 #rho init for bnn layers
use_flipout_layers: False #Use Flipout layers for BNNs, default is Reparameterization layers
moped_init_model: '' #DNN model to intialize MOPED method
moped_delta_factor: 0.5