data: cifar10
arch: vit_b_16
mode: deterministic
aug: False
size: 32
workers: 4
epochs: 400
start_epoch: 0
batch_size: 256
lr: 0.1
step_size: 50
warmup: True
labelsmoothing: False
optimizer: sgd
scheduler: cos
momentum: 0.9
weight_decay: 5.0e-4
saved_models: "saved_models"
logs: "logs/"
resume: True 
evaluate:  False 
pretrained: False 
world_size: 1
rank: 0 
dist_backend: "nccl"
gpu: 3
multiprocessing_distributed: False 
print_freq: 50
seed: 107