data: cifar10
arch: resnet50
aug: False
size: 32
workers: 4
epochs: 400
start_epoch: 0
batch_size: 512
lr: 0.1
step_size: 50
warmup: True
optimizer: sgd
scheduler: cos
momentum: 0.9
weight_decay: 5.0e-4
saved_models: "saved_models"
logs: "logs/"
resume: True 
evaluate:  False 
pretrained: False 
world_size: 1
rank: 0 
dist_backend: "nccl"
gpu: 2
multiprocessing_distributed: False 
print_freq: 50
seed: 107