data: cifar10
arch: vgg16
workers: 4
epochs: 100
start_epoch: 0
batch_size: 512
lr: 0.01
step_size: 20
momentum: 0.9
weight_decay: 1.0e-4
saved_models: "saved_models/"
logs: "logs/"
resume: True 
evaluate:  True 
pretrained: False 
world_size: 1
rank: 0 
dist_backend: "nccl"
gpu: 0
multiprocessing_distributed: False 
print_freq: 10
seed: 1